### ISSUE TITLE
update to 0.8

### ISSUE THREAD

**Issue by croth1** [conda-forge/seaborn-feedstock#6]
@conda-forge/core - is there an easy way to update with the latest smithy, without having smithy locally? In the past up and downgrading conda gave me quite a headache.

The update bot does not seem to send PRs anymore - do we by any chance have a docker image that can do the smithy updates?

**Comment by jakirkham** [comment]
`conda-smithy` and `conda-build-all` supports `conda` 4.3. So shouldn't be an issue on that front. Though `conda-build` still needs to be 2.x.
